version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: clara_n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./dataset:/dataset
      - ./outputs:/outputs
      - ./scripts:/scripts
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODES_EXCLUDE="[]"
